# -*- coding: utf-8 -*-
"""Estatistica Descritiva.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CpV6Ut45Vw4U0WEJTDkgG-0a4sdMCgID
"""

import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt 

import warnings 
warnings.filterwarnings('ignore')

base_iris = sns.load_dataset('iris')
base_iris.head()

# Quantidade de linhas e colunas

base_iris.shape

# Média

base_iris['petal_length'].mean()

# Moda  - é o valor que apresenta a maior frequencia de variavel entre os valores observados 

base_iris['petal_length'].mode()

# Mediana  - posição central dos dados

base_iris['petal_length'].median()

# Medidas Separatrizes - Quartis  q1 25% dos dados , q2 50% dos dados, q3 75% dos dados
base_iris['sepal_length'].describe()

sns.boxplot(base_iris['sepal_length']);

# Medidas de Dispersão
#Amplitude total é a diferença entre o max e o min
base_iris['sepal_length'].max() - base_iris['sepal_length'].min()

# Amplitude Interquartilica 
# a amplitude interquatilica é a diferenca entre o terceiro quartil e o primeiro. essa medida é mais estavel que a amplitude total considerar os valores extremos

base_iris['sepal_length'].describe()[6:7].values - base_iris['sepal_length'].describe()[4:5].values

# Amplitude semi-interquartilica 
# é definifa como a média aritmética da diferença entre a mediana e os quartis
(base_iris['sepal_length'].describe()[6:7].values - base_iris['sepal_length'].describe()[4:5].values) / 2

# Váriancia
# Ema medida de dispersão que mostra quão distantes os valores estão da média

base_iris['sepal_length'].var()

# Desfio Padrão 
# é o resultado positivo da raiz quadrada da variância

base_iris['sepal_length'].std()

# Medidas de Assimetria

# é um indicador da forma da distribuição dos dados
# SIMÉTRICA MÉDIA = MEDIANA = MODA OU AS = 0 
# ASSIMÉTRICA negativa se média <= mediana <= moda as <0 
# ASSIMÉTRICA positiva se moda <= mediada <= média ou as > 0 

# Calculando a simetria 
base_iris['sepal_length'].skew()

sns.kdeplot(base_iris['sepal_length'], color ='blue');

# Medidas de Cutose 
# A medida de curtose é o grau de achatamento da distribuição, é um indicador da forma desta distribuição
# Leptocúrtica  k < 0,263
# Mesocúrtica k = 0,263
# Platicúrtica k > 0,263

base_iris['sepal_length'].kurtosis() #leptocúrtica

# Correlação 
# O coeficiente de correlação de Person pode ter um intervalo de +1 a -1 . um valor
#  de 0 indica que não há associação entre as duas variáveis. Um valor maior que 0 
# indica uma associação positiva. Isto é, á medida que o valor de uma variável aumenta,
# o mesmo acontece o valor da outra variável. Um valor menor que 0 indica uma associação
# negativa. Isto é, a medida que o valor de váriavel aumenta o valor negativo diminui.

base_iris.corr()

sns.heatmap(base_iris.corr(), annot = True);

sns.scatterplot( data= base_iris, x='petal_length', y ='petal_width');

base_iris.corr('spearman')

sns.heatmap(base_iris.corr('spearman'), annot = True);

sns.scatterplot( data= base_iris, x='sepal_length', y ='petal_width');